#+title: Davemacs
#+author: Dave C.

* Introduction

  If I had a nickel for every useless commit message that I used to do
  back in school, I could probably retire early on a yacht.
  But as I don't get paid for shoddy commit messages, I figured I
  ought to document my choices early and coherently.
  In other words, a literate configuration is the new direction.

  Before one can make a program from scratch, you must first
  ~git clone~ the universe.

  #+begin_src shell
    git clone git@github.com:dchesser/.emacs.d.git
  #+end_src

  To modify the source-code, use ~C-c '~ (control-C, then apostrophe)
  in the code blocks.
  Without further ado...

* Me

  #+begin_src emacs-lisp
       (setq user-full-name "Dave Chesser"
             user-mail-address "dave@dchesser.website")
  #+end_src
  
  So the name's Dave. Hi.
  I'm a programmer by trade, so [[https://gnu.org/s/emacs/][GNU Emacs]] was a logical choice in tooling.

  - It's been around for decades, so it's no passing fad.
  - It's popular, so there's almost a package for /everything/.
  - It's scripted via [[https://www.gnu.org/software/emacs/manual/html_node/eintr/][Emacs Lisp]], its dialect of [[https://en.wikipedia.org/wiki/Lisp_(programming_language)][Lisp]], to serve as
    its own computing environment as well as a method of extending
    its capabilities.

* Customizations

  ~M-x customize-group <RET> D <RET>~ for more details.

** Fonts

*** ~D-preferred-fonts-list~

    List of font names to prefer when opening a frame.
    If none of the fonts are available, the default
    will be "Monospace".

*** ~D-preferred-font-size~

    The chosen font size for the font chosen in
    ~D-preferred-fonts-list~.
